[project]
name = "gmail-deleter"
version = "0.1.0"
description = "Gmail cleanup tool to delete old messages"
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client",
    "google-auth-httplib2",
    "google-auth-oauthlib",
]
